### ISSUE TITLE
Tool to Create/Render 3D Floorplans

### ISSUE THREAD

**Issue by Skylion007** [zillow/zind#2]
I didn't see any code that allows the rendering out of the 3D floor plans shown in Fig 1 of the paper and the top of the ReadMe. Will this repo support that feature or is that out of scope?

**Comment by ivaylob-zg** [comment]
Fig. 1 from the main paper is a result of an internal script that transformed ZInD to a sub-set of the [S3D format](https://github.com/bertjiazheng/Structured3D/blob/master/data_organization.md).). We then used their open-source [visualization tools](https://github.com/bertjiazheng/Structured3D#tools),  as cited.

We were not originally planning on polishing and releasing that code, but it seems there is some interest in releasing those conversion scripts to help the community move faster.

We will scope the work required to polish those scripts and will update you once they are available, but this will most likely happen in the next few weeks.

**Comment by lichenwangzillow** [comment]
We provided python scripts which convert original ZInD data format to Structure3D format with minimal modifications, and render the converted samples for visualization purposes. The modifications are due to a few extra components (e.g., windows, doors, and openings). In addition, we further provided the modified visualization scripts for visualizing the converted ZInD samples in an interactive manner.

The conversion and rendering codes are provided in a new branch “s3d”. You can find the details in this link.
